### ISSUE TITLE
Service stopped on 7/28/2020

### ISSUE THREAD

**Issue by DrewsephA** [xDHILEx/Shower-Thoughts#1]
I signed up for the service when it was first posted to reddit 5 years ago, and have looked forward to it every day. On July 29th, I didn't receive a text with the daily ShowerThought, and haven't received one since. If this project is shut down, I will be sad, but I understand, I was just curious. 

Thank you!

**Comment by xDHILEx** [comment]
Wow, first of all, thank you.

Secondly, I took that site offline within days of posting it. Twilio prices
were much higher back then and being more or less a joke (of a) service I
couldn't justify the cost or the ethical dilemma of how easily it could be
abused.

You're welcome to pull or fork the code and host it yourself. There's a
config file you can throw all your Twilio info into and it should be good
to go. However, if it's truly been 5 years it may need some adjustments.

**Comment by xDHILEx** [comment]
Bruh. I have a -$42 balance on Twilio 😒
